fn_params_layout = "Compressed"
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
max_width = 120

# unstable:
# wrap_comments = true
# normalize_comments = true
# unstable_features = true
# condense_wildcard_suffixes = true
# overflow_delimited_expr = true
# comment_width = 100
# normalize_doc_attributes = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# reorder_impl_items = true
