name: Flake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build ante and ante-ls
        run: nix build .#ante .#ante-ls --print-build-logs
      - name: Run flake checks (tests)
        run: nix flake check --print-build-logs
